### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by okanduzyel** [chrisdonahue/wavegan#116]
Hi, 

I cloned the project and I guess installed all required libraries but unfortunately can not run it. I got this output while I want to run.

```
(base) okanduzyel@Okan-MacBook-Pro wavegan % python train_wavegan.py train ./train \
        --data_dir ./Users/okanduzyel/Downloads/IDMT-SMT-DRUMS-V2/audio \
        --data_first_slice \
        --data_pad_end \
        --data_fast_wav
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/wavegan/train_wavegan.py", line 12, in <module>
    import tensorflow as tf
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 36, in <module>
    from tensorflow.python import pywrap_tfe
  File "/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/pywrap_tfe.py", line 29, in <module>
    from tensorflow.python._pywrap_tfe import *
ImportError: dlopen(/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tfe.so, 0x0002): Library not loaded: @rpath/_pywrap_tensorflow_internal.so
  Referenced from: /Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tfe.so
  Reason: tried: '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utfe.so___Utensorflow/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal_Umacos___Utensorflow_Spython/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/../_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utfe.so___Utensorflow/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal_Umacos___Utensorflow_Spython/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/../_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/bin/../lib/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/lib/_pywrap_tensorflow_internal.so' (no such file), '/Users/okanduzyel/opt/anaconda3/bin/../lib/_pywrap_tensorflow_internal.so' (no such file), '/usr/local/lib/_pywrap_tensorflow_internal.so' (no such file), '/usr/lib/_pywrap_tensorflow_internal.so' (no such file)
(base) okanduzyel@Okan-MacBook-Pro wavegan % 
```

**Comment by mattjwarren** [comment]
wha versions of tf and python do you have?

**Comment by atthom** [comment]
This is because you are using TensorFlow 2.X and wavegan require tensorflow-gpu==1.12.0
