### ISSUE TITLE
Bias not found in Checkpoint error

### ISSUE THREAD

**Issue by CryoScythe** [chrisdonahue/wavegan#12]
An error is caused when running the **train_specgan** script over **sc09** dataset in **Train** mode. The error persisted through different systems.

The execution was done as follows:
train_specgan -> **train_wavegan**  (gives error)
train_specgan -> train_wavegan(create moments) -> **train_wavegan** (gives error)
Following is the traceback taken from PyCharm's console:

```
F:\Apps\Python3\python.exe C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py train ./train --data_dir ./sc09 --data_moments_fp ./train/moments.pkl
WARNING:tensorflow:From C:\Users\admin\PycharmProjects\WaveGAN\loader.py:59: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
--------------------------------------------------------------------------------
Generator vars
[100, 16384] (1638400): G/z_project/dense/kernel:0
[16384] (16384): G/z_project/dense/bias:0
[5, 5, 512, 1024] (13107200): G/upconv_0/conv2d_transpose/kernel:0
[512] (512): G/upconv_0/conv2d_transpose/bias:0
[5, 5, 256, 512] (3276800): G/upconv_1/conv2d_transpose/kernel:0
[256] (256): G/upconv_1/conv2d_transpose/bias:0
[5, 5, 128, 256] (819200): G/upconv_2/conv2d_transpose/kernel:0
[128] (128): G/upconv_2/conv2d_transpose/bias:0
[5, 5, 64, 128] (204800): G/upconv_3/conv2d_transpose/kernel:0
[64] (64): G/upconv_3/conv2d_transpose/bias:0
[5, 5, 1, 64] (1600): G/upconv_4/conv2d_transpose/kernel:0
[1] (1): G/upconv_4/conv2d_transpose/bias:0
Total params: 19065345 (72.73 MB)
--------------------------------------------------------------------------------
Discriminator vars
[5, 5, 1, 64] (1600): D/downconv_0/conv2d/kernel:0
[64] (64): D/downconv_0/conv2d/bias:0
[5, 5, 64, 128] (204800): D/downconv_1/conv2d/kernel:0
[128] (128): D/downconv_1/conv2d/bias:0
[5, 5, 128, 256] (819200): D/downconv_2/conv2d/kernel:0
[256] (256): D/downconv_2/conv2d/bias:0
[5, 5, 256, 512] (3276800): D/downconv_3/conv2d/kernel:0
[512] (512): D/downconv_3/conv2d/bias:0
[5, 5, 512, 1024] (13107200): D/downconv_4/conv2d/kernel:0
[1024] (1024): D/downconv_4/conv2d/bias:0
[16384, 1] (16384): D/output/dense/kernel:0
[1] (1): D/output/dense/bias:0
Total params: 17427969 (66.48 MB)
--------------------------------------------------------------------------------
2018-09-26 23:24:45.642928: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-09-26 23:24:45.748523: W T:\src\github\tensorflow\tensorflow\core\framework\op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key D/downconv_0/conv2d/bias not found in checkpoint
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key D/downconv_0/conv2d/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1725, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key D/downconv_0/conv2d/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py", line 693, in <module>
    train(fps, args)
  File "C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py", line 263, in train
    save_summaries_secs=args.train_summary_secs) as sess:
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 421, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 832, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 555, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1018, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1023, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 712, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 474, in create_session
    self._scaffold.finalize()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 853, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
    self.build()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 772, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 450, in _AddShardedRestoreOps
    name="restore_shard"))
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key D/downconv_0/conv2d/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1737, in restore
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 348, in get_tensor
    status)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py", line 693, in <module>
    train(fps, args)
  File "C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py", line 263, in train
    save_summaries_secs=args.train_summary_secs) as sess:
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 421, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 832, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 555, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1018, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1023, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 712, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 483, in create_session
    init_fn=self._scaffold.init_fn)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\session_manager.py", line 281, in prepare_session
    config=config)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\session_manager.py", line 211, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1743, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key D/downconv_0/conv2d/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py", line 693, in <module>
    train(fps, args)
  File "C:/Users/admin/PycharmProjects/WaveGAN/train_specgan.py", line 263, in train
    save_summaries_secs=args.train_summary_secs) as sess:
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 421, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 832, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 555, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1018, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 1023, in _create_session
    return self._sess_creator.create_session()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 712, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 474, in create_session
    self._scaffold.finalize()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 853, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1281, in __init__
    self.build()
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 772, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 450, in _AddShardedRestoreOps
    name="restore_shard"))
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1546, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key D/downconv_0/conv2d/bias not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


Process finished with exit code 1
```

**Comment by chrisdonahue** [comment]
I'm not really sure what you mean by this:
```
train_specgan -> train_wavegan (gives error)
train_specgan -> train_wavegan(create moments) -> train_wavegan (gives error)
```

SpecGAN/WaveGAN are separate models. You do not need to train a SpecGAN in order to train a WaveGAN and vice versa. I think what's happening is you're trying to load specgan checkpoints in the wavegan code. Change the training directory flag when running either script.

Reopen if this does not resolve your issue
