### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by Reagan1947** [chrisdonahue/wavegan#68]
I used anaconda  created an enviroment as 'readme.file' required:
```
pip install tensorflow-gpu==1.12.0
pip install scipy==1.0.0
pip install matplotlib==3.0.2
pip install librosa==0.6.2
```
And i user my dataset which is  wav type human speech to train. use this code below:
`python train_specgan.py train ./train --data_dir ./train_wav`

I got this error meessage below:

```
Training has started. Please use 'tensorboard --logdir=./train' to monitor.
Traceback (most recent call last):
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: G_z_rms_batch
	 [[{{node G_z_rms_batch}} = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](G_z_rms_batch/tag, Sqrt/_655)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_wavegan.py", line 654, in <module>
    train(fps, args)
  File "train_wavegan.py", line 202, in train
    sess.run(D_train_op)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: G_z_rms_batch
	 [[node G_z_rms_batch (defined at train_wavegan.py:70)  = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](G_z_rms_batch/tag, Sqrt/_655)]]

Caused by op 'G_z_rms_batch', defined at:
  File "train_wavegan.py", line 654, in <module>
    train(fps, args)
  File "train_wavegan.py", line 70, in train
    tf.summary.histogram('G_z_rms_batch', G_z_rms)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/summary/summary.py", line 187, in histogram
    tag=tag, values=values, name=scope)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 284, in histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/dc2-user/anaconda3/envs/wave_gan/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: G_z_rms_batch
	 [[node G_z_rms_batch (defined at train_wavegan.py:70)  = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](G_z_rms_batch/tag, Sqrt/_655)]]

```

**Comment by Reagan1947** [comment]
Delete the train file dict will solve it.
